library(TMB)
compile("linreg.cpp")
dyn.load("linreg.so")
set.seed(123)
data <- list(Y=rnorm(100)+1:100,x=1:100)
parameters <- list(a=0,b=0,logSigma=0)
obj <- MakeADFun(data,parameters)
opt <- do.call("optim",obj)
sdreport(obj)
